"""Common ORM mixins: UUID primary key, timestamps, soft-delete (trash)."""
from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, func, text
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column


class UUIDPrimaryKeyMixin:
    id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=text("gen_random_uuid()"),
    )


class TimestampMixin:
    """`created_at`/`updated_at` are generated by the database clock.

    `eager_defaults` matters: a server-generated `onupdate` value is unknown to Python
    after an UPDATE, so without it the attribute is left expired and the next read -
    which is how every write endpoint builds its response - tries to lazy-load. Under
    asyncio that raises `MissingGreenlet` and the request fails with a 500. Fetching
    the values in the same statement (RETURNING) is what makes an async server able to
    report the timestamp it just wrote.
    """

    __mapper_args__ = {"eager_defaults": True}

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )


class SoftDeleteMixin:
    """Trash / recycle-bin support. Default retention handled by a worker job.

    Rows are never hard-deleted by default (see TRASH / SOFT DELETE in the spec).
    """

    deleted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
