"""bootstrap schema

Revision ID: 0001_bootstrap
Revises:
Create Date: 2026-10-06

Explicit, deterministic initial schema for the self-hosted platform.

This revision is a frozen snapshot: every table/index/constraint below is
spelled out literally (op.create_table / op.create_index / explicit
sa.ForeignKeyConstraint / sa.UniqueConstraint). It does NOT import or read
`app.models` / `Base.metadata` at execution time, so running
`alembic upgrade head` always reproduces exactly this historical schema,
even if the ORM models change later.

From here on, iterate with granular autogenerated revisions:
    alembic revision --autogenerate -m "add <x>"
so each schema change is reviewable in isolation and the down migrations stay
correct. Do not hand-edit this bootstrap file after real deployments exist.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001_bootstrap"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "admin_user",
        sa.Column("username", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("session_epoch", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    op.create_table(
        "audit_log",
        sa.Column("actor_type", sa.String(length=16), nullable=False),
        sa.Column("actor_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("action", sa.String(length=96), nullable=False),
        sa.Column("target_type", sa.String(length=64), nullable=True),
        sa.Column("target_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    op.create_table(
        "backup",
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("trigger", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("restored_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    op.create_table(
        "catalog",
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("parent_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("learning_language", sa.String(length=16), nullable=True),
        sa.Column("level", sa.String(length=32), nullable=True),
        sa.Column("shuffle_default", sa.Boolean(), nullable=False),
        sa.Column("known_states_enabled", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=8), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["catalog.id"], name="fk_catalog_parent_id_catalog", ondelete="SET NULL"
        ),
    )
    op.create_table(
        "exam",
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=9), nullable=False),
        sa.Column("learning_language", sa.String(length=16), nullable=True),
        sa.Column("level", sa.String(length=32), nullable=True),
        sa.Column("available_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("available_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("must_finish_before_close", sa.Boolean(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=True),
        sa.Column("passing_score", sa.Float(), nullable=True),
        sa.Column("shuffle_questions", sa.Boolean(), nullable=False),
        sa.Column("shuffle_options", sa.Boolean(), nullable=False),
        sa.Column("resume_after_disconnect", sa.Boolean(), nullable=False),
        sa.Column("restrict_copy_paste", sa.Boolean(), nullable=False),
        sa.Column("monitor_tab_switch", sa.Boolean(), nullable=False),
        sa.Column("tab_switch_limit", sa.Integer(), nullable=True),
        sa.Column("tab_switch_action", sa.String(length=32), nullable=True),
        sa.Column("allow_previous", sa.Boolean(), nullable=False),
        sa.Column("feedback_timing", sa.String(length=13), nullable=False),
        sa.Column("show_correct_answers", sa.Boolean(), nullable=False),
        sa.Column("show_explanations", sa.Boolean(), nullable=False),
        sa.Column("result_visibility", sa.String(length=32), nullable=False),
        sa.Column("partial_scoring_enabled", sa.Boolean(), nullable=False),
        sa.Column("negative_marking_enabled", sa.Boolean(), nullable=False),
        sa.Column("grading_mode", sa.String(length=11), nullable=False),
        sa.Column("auto_submit_on_expiry", sa.Boolean(), nullable=False),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_table(
        "group",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("color", sa.String(length=32), nullable=True),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_table(
        "language",
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("name_en", sa.String(length=120), nullable=False),
        sa.Column("native_name", sa.String(length=120), nullable=True),
        sa.Column("is_ui", sa.Boolean(), nullable=False),
        sa.Column("is_learning", sa.Boolean(), nullable=False),
        sa.Column("is_translation", sa.Boolean(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    op.create_table(
        "media_asset",
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("original_filename", sa.String(length=500), nullable=True),
        sa.Column("mime_type", sa.String(length=120), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("checksum", sa.String(length=128), nullable=True),
        sa.Column("source_origin", sa.String(length=32), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_table(
        "source_file",
        sa.Column("title", sa.String(length=400), nullable=False),
        sa.Column("original_filename", sa.String(length=500), nullable=True),
        sa.Column("mime_type", sa.String(length=120), nullable=True),
        sa.Column("storage_key", sa.String(length=500), nullable=True),
        sa.Column("keep_original", sa.Boolean(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("language", sa.String(length=16), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_table(
        "student",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("surname", sa.String(length=120), nullable=False),
        sa.Column("username", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=8), nullable=False),
        sa.Column("ui_language", sa.String(length=16), nullable=True),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_table(
        "system_setting",
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.UniqueConstraint("category", "key", name="uq_setting_category_key"),
    )
    op.create_table(
        "tag",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("color", sa.String(length=32), nullable=True),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    op.create_table(
        "topic",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("parent_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("level_path", sa.String(length=700), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=True),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["topic.id"], name="fk_topic_parent_id_topic", ondelete="CASCADE"
        ),
    )
    op.create_table(
        "admin_recovery_code",
        sa.Column("admin_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("code_hash", sa.String(length=255), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("superseded", sa.Boolean(), nullable=False),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["admin_user.id"],
            name="fk_admin_recovery_code_admin_id_admin_user",
            ondelete="CASCADE",
        ),
    )
    op.create_table(
        "catalog_item",
        sa.Column("catalog_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("ref_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["catalog_id"],
            ["catalog.id"],
            name="fk_catalog_item_catalog_id_catalog",
            ondelete="CASCADE",
        ),
    )
    op.create_table(
        "exam_assignment",
        sa.Column("exam_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("student_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("group_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["exam_id"], ["exam.id"], name="fk_exam_assignment_exam_id_exam", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["group_id"], ["group.id"], name="fk_exam_assignment_group_id_group", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.id"],
            name="fk_exam_assignment_student_id_student",
            ondelete="CASCADE",
        ),
    )
    op.create_table(
        "exam_attempt",
        sa.Column("exam_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("student_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=14), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("server_seconds_used", sa.Integer(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("max_score", sa.Float(), nullable=True),
        sa.Column("passed", sa.Boolean(), nullable=True),
        sa.Column("tab_switch_count", sa.Integer(), nullable=False),
        sa.Column("blueprint", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["exam_id"], ["exam.id"], name="fk_exam_attempt_exam_id_exam", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.id"],
            name="fk_exam_attempt_student_id_student",
            ondelete="CASCADE",
        ),
    )
    op.create_table(
        "exam_section",
        sa.Column("exam_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("shuffle_items", sa.Boolean(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["exam_id"], ["exam.id"], name="fk_exam_section_exam_id_exam", ondelete="CASCADE"
        ),
    )
    op.create_table(
        "export_job",
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("fmt", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("filters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=True),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column("requested_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["admin_user.id"],
            name="fk_export_job_requested_by_admin_user",
            ondelete="SET NULL",
        ),
    )
    op.create_table(
        "favorite",
        sa.Column("student_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("ref_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.id"],
            name="fk_favorite_student_id_student",
            ondelete="CASCADE",
        ),
    )
    op.create_table(
        "group_membership",
        sa.Column("group_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("student_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["group.id"],
            name="fk_group_membership_group_id_group",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.id"],
            name="fk_group_membership_student_id_student",
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint("group_id", "student_id", name="uq_group_student"),
    )
    op.create_table(
        "import_job",
        sa.Column("source_file_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("profile", sa.String(length=120), nullable=True),
        sa.Column("auto_mode", sa.Boolean(), nullable=False),
        sa.Column("progress", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["source_file_id"],
            ["source_file.id"],
            name="fk_import_job_source_file_id_source_file",
            ondelete="SET NULL",
        ),
    )
    op.create_table(
        "listening",
        sa.Column("title", sa.String(length=400), nullable=False),
        sa.Column("media_asset_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("language", sa.String(length=16), nullable=True),
        sa.Column("level", sa.String(length=32), nullable=True),
        sa.Column("transcript", sa.Text(), nullable=True),
        sa.Column("transcript_source", sa.String(length=32), nullable=True),
        sa.Column("transcript_timestamps", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("replay_limit", sa.Integer(), nullable=True),
        sa.Column("allow_pause", sa.Boolean(), nullable=False),
        sa.Column("allow_seek", sa.Boolean(), nullable=False),
        sa.Column("show_transcript", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=8), nullable=False),
        sa.Column("source_file_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["media_asset_id"],
            ["media_asset.id"],
            name="fk_listening_media_asset_id_media_asset",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_file_id"],
            ["source_file.id"],
            name="fk_listening_source_file_id_source_file",
            ondelete="SET NULL",
        ),
    )
    op.create_table(
        "notification",
        sa.Column("audience", sa.String(length=7), nullable=False),
        sa.Column("student_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("link", sa.String(length=500), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.id"],
            name="fk_notification_student_id_student",
            ondelete="CASCADE",
        ),
    )
    op.create_table(
        "reading",
        sa.Column("title", sa.String(length=400), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=True),
        sa.Column("level", sa.String(length=32), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=True),
        sa.Column("layout", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=8), nullable=False),
        sa.Column("source_file_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_file_id"],
            ["source_file.id"],
            name="fk_reading_source_file_id_source_file",
            ondelete="SET NULL",
        ),
    )
    op.create_table(
        "student_access_key",
        sa.Column("student_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("key_hash", sa.String(length=255), nullable=False),
        sa.Column("key_prefix", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=7), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.id"],
            name="fk_student_access_key_student_id_student",
            ondelete="CASCADE",
        ),
    )
    op.create_table(
        "student_note",
        sa.Column("student_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("author_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["admin_user.id"],
            name="fk_student_note_author_id_admin_user",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.id"],
            name="fk_student_note_student_id_student",
            ondelete="CASCADE",
        ),
    )
    op.create_table(
        "student_session",
        sa.Column("student_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_location", sa.String(length=200), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("terminated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.id"],
            name="fk_student_session_student_id_student",
            ondelete="CASCADE",
        ),
    )
    op.create_table(
        "vocabulary_entry",
        sa.Column("word", sa.String(length=300), nullable=False),
        sa.Column("learning_language", sa.String(length=16), nullable=True),
        sa.Column("definition", sa.Text(), nullable=True),
        sa.Column("ipa", sa.String(length=200), nullable=True),
        sa.Column("part_of_speech", sa.String(length=64), nullable=True),
        sa.Column("level", sa.String(length=32), nullable=True),
        sa.Column("audio_asset_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("synonyms", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("antonyms", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("source_file_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("status", sa.String(length=8), nullable=False),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["audio_asset_id"],
            ["media_asset.id"],
            name="fk_vocabulary_entry_audio_asset_id_media_asset",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_file_id"],
            ["source_file.id"],
            name="fk_vocabulary_entry_source_file_id_source_file",
            ondelete="SET NULL",
        ),
    )
    op.create_table(
        "import_item",
        sa.Column("job_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("detected_kind", sa.String(length=64), nullable=True),
        sa.Column("detected_type", sa.String(length=64), nullable=True),
        sa.Column("source_page", sa.Integer(), nullable=True),
        sa.Column("source_sheet", sa.String(length=200), nullable=True),
        sa.Column("crop_storage_key", sa.String(length=500), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("decision", sa.String(length=8), nullable=False),
        sa.Column("extracted", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("corrected", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("result_ref_type", sa.String(length=64), nullable=True),
        sa.Column("result_ref_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["import_job.id"],
            name="fk_import_item_job_id_import_job",
            ondelete="CASCADE",
        ),
    )
    op.create_table(
        "listening_question_set",
        sa.Column("listening_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=True),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("start_seconds", sa.Float(), nullable=True),
        sa.Column("end_seconds", sa.Float(), nullable=True),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["listening_id"],
            ["listening.id"],
            name="fk_listening_question_set_listening_id_listening",
            ondelete="CASCADE",
        ),
    )
    op.create_table(
        "question",
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=8), nullable=False),
        sa.Column("context_kind", sa.String(length=11), nullable=False),
        sa.Column("reading_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("listening_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("partial_scoring", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("negative_scoring", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("level", sa.String(length=32), nullable=True),
        sa.Column("difficulty", sa.Integer(), nullable=True),
        sa.Column("learning_language", sa.String(length=16), nullable=True),
        sa.Column("source_file_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("source_page", sa.Integer(), nullable=True),
        sa.Column("source_sheet", sa.String(length=200), nullable=True),
        sa.Column("extraction_method", sa.String(length=64), nullable=True),
        sa.Column("import_job_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("teacher_notes", sa.Text(), nullable=True),
        sa.Column("media_asset_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["import_job_id"],
            ["import_job.id"],
            name="fk_question_import_job_id_import_job",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["listening_id"],
            ["listening.id"],
            name="fk_question_listening_id_listening",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["media_asset_id"],
            ["media_asset.id"],
            name="fk_question_media_asset_id_media_asset",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reading_id"],
            ["reading.id"],
            name="fk_question_reading_id_reading",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_file_id"],
            ["source_file.id"],
            name="fk_question_source_file_id_source_file",
            ondelete="SET NULL",
        ),
    )
    op.create_table(
        "reading_question_set",
        sa.Column("reading_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=True),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["reading_id"],
            ["reading.id"],
            name="fk_reading_question_set_reading_id_reading",
            ondelete="CASCADE",
        ),
    )
    op.create_table(
        "vocabulary_example",
        sa.Column("entry_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("sentence", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=True),
        sa.Column("translation", sa.Text(), nullable=True),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["vocabulary_entry.id"],
            name="fk_vocabulary_example_entry_id_vocabulary_entry",
            ondelete="CASCADE",
        ),
    )
    op.create_table(
        "vocabulary_tag",
        sa.Column("vocabulary_entry_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("tag_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tag.id"], name="fk_vocabulary_tag_tag_id_tag", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["vocabulary_entry_id"],
            ["vocabulary_entry.id"],
            name="fk_vocabulary_tag_vocabulary_entry_id_vocabulary_entry",
            ondelete="CASCADE",
        ),
    )
    op.create_table(
        "vocabulary_translation",
        sa.Column("entry_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["vocabulary_entry.id"],
            name="fk_vocabulary_translation_entry_id_vocabulary_entry",
            ondelete="CASCADE",
        ),
    )
    op.create_table(
        "activity_event",
        sa.Column("student_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=True),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("human_summary", sa.Text(), nullable=True),
        sa.Column("context_type", sa.String(length=32), nullable=True),
        sa.Column("context_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("ref_question_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("correct", sa.Boolean(), nullable=True),
        sa.Column("time_spent_seconds", sa.Integer(), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("device", sa.String(length=120), nullable=True),
        sa.Column("browser", sa.String(length=120), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["ref_question_id"],
            ["question.id"],
            name="fk_activity_event_ref_question_id_question",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.id"],
            name="fk_activity_event_student_id_student",
            ondelete="CASCADE",
        ),
    )
    op.create_table(
        "question_report",
        sa.Column("student_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("question_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("handled", sa.Boolean(), nullable=False),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question.id"],
            name="fk_question_report_question_id_question",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.id"],
            name="fk_question_report_student_id_student",
            ondelete="CASCADE",
        ),
    )
    op.create_table(
        "question_tag",
        sa.Column("question_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("tag_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question.id"],
            name="fk_question_tag_question_id_question",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tag.id"], name="fk_question_tag_tag_id_tag", ondelete="CASCADE"
        ),
    )
    op.create_table(
        "question_topic",
        sa.Column("question_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("topic_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question.id"],
            name="fk_question_topic_question_id_question",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"], ["topic.id"], name="fk_question_topic_topic_id_topic", ondelete="CASCADE"
        ),
    )
    op.create_table(
        "question_version",
        sa.Column("question_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("change_note", sa.Text(), nullable=True),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question.id"],
            name="fk_question_version_question_id_question",
            ondelete="CASCADE",
        ),
    )
    op.create_table(
        "exam_item",
        sa.Column("exam_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("section_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("ref_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("question_version_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("points", sa.Float(), nullable=True),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["exam_id"], ["exam.id"], name="fk_exam_item_exam_id_exam", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["question_version_id"],
            ["question_version.id"],
            name="fk_exam_item_question_version_id_question_version",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["exam_section.id"],
            name="fk_exam_item_section_id_exam_section",
            ondelete="CASCADE",
        ),
    )
    op.create_table(
        "attempt_answer",
        sa.Column("attempt_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("exam_item_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("question_version_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("correct", sa.Boolean(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("graded", sa.Boolean(), nullable=False),
        sa.Column("needs_manual_review", sa.Boolean(), nullable=False),
        sa.Column("time_spent_seconds", sa.Integer(), nullable=True),
        sa.Column("changed_count", sa.Integer(), nullable=False),
        sa.Column("flagged", sa.Boolean(), nullable=False),
        sa.Column("client_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["exam_attempt.id"],
            name="fk_attempt_answer_attempt_id_exam_attempt",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["exam_item_id"],
            ["exam_item.id"],
            name="fk_attempt_answer_exam_item_id_exam_item",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["question_version_id"],
            ["question_version.id"],
            name="fk_attempt_answer_question_version_id_question_version",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "manual_review",
        sa.Column("attempt_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("answer_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("reviewed", sa.Boolean(), nullable=False),
        sa.Column("ai_suggestion", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("final_score", sa.Float(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewer_note", sa.Text(), nullable=True),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["answer_id"],
            ["attempt_answer.id"],
            name="fk_manual_review_answer_id_attempt_answer",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["exam_attempt.id"],
            name="fk_manual_review_attempt_id_exam_attempt",
            ondelete="CASCADE",
        ),
    )
    op.create_table(
        "teacher_feedback",
        sa.Column("attempt_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("answer_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("student_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["answer_id"],
            ["attempt_answer.id"],
            name="fk_teacher_feedback_answer_id_attempt_answer",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["exam_attempt.id"],
            name="fk_teacher_feedback_attempt_id_exam_attempt",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.id"],
            name="fk_teacher_feedback_student_id_student",
            ondelete="CASCADE",
        ),
    )

    op.create_index("ix_admin_user_username", "admin_user", ["username"], unique=True)
    op.create_index("ix_audit_actor_time", "audit_log", ["actor_type", "created_at"])
    op.create_index("ix_audit_log_action", "audit_log", ["action"])
    op.create_index("ix_audit_log_actor_id", "audit_log", ["actor_id"])
    op.create_index("ix_audit_log_target_id", "audit_log", ["target_id"])
    op.create_index("ix_catalog_learning_language", "catalog", ["learning_language"])
    op.create_index("ix_catalog_parent_id", "catalog", ["parent_id"])
    op.create_index("ix_exam_learning_language", "exam", ["learning_language"])
    op.create_index("ix_language_code", "language", ["code"], unique=True)
    op.create_index("ix_media_asset_checksum", "media_asset", ["checksum"])
    op.create_index("ix_student_status_deleted", "student", ["status", "deleted_at"])
    op.create_index("ix_student_username", "student", ["username"], unique=True)
    op.create_index("ix_system_setting_category", "system_setting", ["category"])
    op.create_index("ix_tag_name", "tag", ["name"], unique=True)
    op.create_index("ix_topic_parent_id", "topic", ["parent_id"])
    op.create_index("ix_topic_parent_name", "topic", ["parent_id", "name"])
    op.create_index("ix_admin_recovery_code_admin_id", "admin_recovery_code", ["admin_id"])
    op.create_index("ix_catalog_item_catalog_id", "catalog_item", ["catalog_id"])
    op.create_index("ix_catalog_item_order", "catalog_item", ["catalog_id", "position"])
    op.create_index("ix_catalog_item_ref_id", "catalog_item", ["ref_id"])
    op.create_index(
        "ix_assignment_target", "exam_assignment", ["exam_id", "student_id", "group_id"]
    )
    op.create_index("ix_exam_assignment_exam_id", "exam_assignment", ["exam_id"])
    op.create_index("ix_exam_assignment_group_id", "exam_assignment", ["group_id"])
    op.create_index("ix_exam_assignment_student_id", "exam_assignment", ["student_id"])
    op.create_index("ix_exam_attempt_exam_id", "exam_attempt", ["exam_id"])
    op.create_index("ix_exam_attempt_session_id", "exam_attempt", ["session_id"])
    op.create_index("ix_exam_attempt_student_id", "exam_attempt", ["student_id"])
    op.create_index("ix_exam_section_exam_id", "exam_section", ["exam_id"])
    op.create_index("ix_favorite_ref_id", "favorite", ["ref_id"])
    op.create_index("ix_favorite_student_id", "favorite", ["student_id"])
    op.create_index("ix_favorite_unique", "favorite", ["student_id", "kind", "ref_id"], unique=True)
    op.create_index("ix_group_membership_group_id", "group_membership", ["group_id"])
    op.create_index("ix_group_membership_student_id", "group_membership", ["student_id"])
    op.create_index("ix_import_job_source_file_id", "import_job", ["source_file_id"])
    op.create_index("ix_listening_language", "listening", ["language"])
    op.create_index("ix_notif_unread", "notification", ["audience", "read_at", "student_id"])
    op.create_index("ix_notification_kind", "notification", ["kind"])
    op.create_index("ix_notification_student_id", "notification", ["student_id"])
    op.create_index("ix_reading_language", "reading", ["language"])
    op.create_index("ix_student_access_key_student_id", "student_access_key", ["student_id"])
    op.create_index(
        "uq_student_access_key_active",
        "student_access_key",
        ["student_id"],
        unique=True,
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.create_index("ix_student_note_student_id", "student_note", ["student_id"])
    op.create_index(
        "ix_student_session_active",
        "student_session",
        ["student_id", "terminated_at", "expires_at"],
    )
    op.create_index("ix_student_session_session_id", "student_session", ["session_id"], unique=True)
    op.create_index("ix_student_session_student_id", "student_session", ["student_id"])
    op.create_index(
        "ix_vocabulary_entry_learning_language", "vocabulary_entry", ["learning_language"]
    )
    op.create_index("ix_vocabulary_entry_word", "vocabulary_entry", ["word"])
    op.create_index("ix_import_item_job_id", "import_item", ["job_id"])
    op.create_index(
        "ix_listening_question_set_listening_id", "listening_question_set", ["listening_id"]
    )
    op.create_index("ix_question_learning_language", "question", ["learning_language"])
    op.create_index("ix_question_level", "question", ["level"])
    op.create_index("ix_question_level_lang", "question", ["level", "learning_language"])
    op.create_index("ix_question_listening_id", "question", ["listening_id"])
    op.create_index("ix_question_reading_id", "question", ["reading_id"])
    op.create_index("ix_question_source_file_id", "question", ["source_file_id"])
    op.create_index("ix_question_type", "question", ["type"])
    op.create_index("ix_question_type_status", "question", ["type", "status"])
    op.create_index("ix_reading_question_set_reading_id", "reading_question_set", ["reading_id"])
    op.create_index("ix_vocabulary_example_entry_id", "vocabulary_example", ["entry_id"])
    op.create_index(
        "ix_vocab_translation_entry_lang", "vocabulary_translation", ["entry_id", "language"]
    )
    op.create_index("ix_vocabulary_translation_entry_id", "vocabulary_translation", ["entry_id"])
    op.create_index("ix_activity_category", "activity_event", ["category", "occurred_at"])
    op.create_index("ix_activity_event_category", "activity_event", ["category"])
    op.create_index("ix_activity_event_context_id", "activity_event", ["context_id"])
    op.create_index("ix_activity_event_event_type", "activity_event", ["event_type"])
    op.create_index("ix_activity_event_occurred_at", "activity_event", ["occurred_at"])
    op.create_index("ix_activity_event_session_id", "activity_event", ["session_id"])
    op.create_index("ix_activity_event_student_id", "activity_event", ["student_id"])
    op.create_index("ix_activity_student_time", "activity_event", ["student_id", "occurred_at"])
    op.create_index("ix_question_report_question_id", "question_report", ["question_id"])
    op.create_index("ix_question_report_student_id", "question_report", ["student_id"])
    op.create_index("ix_question_tag_question_id", "question_tag", ["question_id"])
    op.create_index("ix_question_tag_tag_id", "question_tag", ["tag_id"])
    op.create_index("ix_question_topic_question_id", "question_topic", ["question_id"])
    op.create_index("ix_question_topic_topic_id", "question_topic", ["topic_id"])
    op.create_index("ix_question_version_question_id", "question_version", ["question_id"])
    op.create_index(
        "ix_question_version_qv", "question_version", ["question_id", "version"], unique=True
    )
    op.create_index("ix_exam_item_exam_id", "exam_item", ["exam_id"])
    op.create_index("ix_exam_item_question_version_id", "exam_item", ["question_version_id"])
    op.create_index("ix_exam_item_ref_id", "exam_item", ["ref_id"])
    op.create_index("ix_exam_item_section_id", "exam_item", ["section_id"])
    op.create_index(
        "ix_answer_attempt_item", "attempt_answer", ["attempt_id", "exam_item_id"], unique=True
    )
    op.create_index("ix_attempt_answer_attempt_id", "attempt_answer", ["attempt_id"])
    op.create_index("ix_attempt_answer_exam_item_id", "attempt_answer", ["exam_item_id"])
    op.create_index(
        "ix_attempt_answer_question_version_id", "attempt_answer", ["question_version_id"]
    )
    op.create_index("ix_manual_review_answer_id", "manual_review", ["answer_id"])
    op.create_index("ix_manual_review_attempt_id", "manual_review", ["attempt_id"])
    op.create_index("ix_teacher_feedback_answer_id", "teacher_feedback", ["answer_id"])
    op.create_index("ix_teacher_feedback_attempt_id", "teacher_feedback", ["attempt_id"])
    op.create_index("ix_teacher_feedback_student_id", "teacher_feedback", ["student_id"])


def downgrade() -> None:
    op.drop_index("ix_teacher_feedback_student_id", table_name="teacher_feedback")
    op.drop_index("ix_teacher_feedback_attempt_id", table_name="teacher_feedback")
    op.drop_index("ix_teacher_feedback_answer_id", table_name="teacher_feedback")
    op.drop_index("ix_manual_review_attempt_id", table_name="manual_review")
    op.drop_index("ix_manual_review_answer_id", table_name="manual_review")
    op.drop_index("ix_attempt_answer_question_version_id", table_name="attempt_answer")
    op.drop_index("ix_attempt_answer_exam_item_id", table_name="attempt_answer")
    op.drop_index("ix_attempt_answer_attempt_id", table_name="attempt_answer")
    op.drop_index("ix_answer_attempt_item", table_name="attempt_answer")
    op.drop_index("ix_exam_item_section_id", table_name="exam_item")
    op.drop_index("ix_exam_item_ref_id", table_name="exam_item")
    op.drop_index("ix_exam_item_question_version_id", table_name="exam_item")
    op.drop_index("ix_exam_item_exam_id", table_name="exam_item")
    op.drop_index("ix_question_version_qv", table_name="question_version")
    op.drop_index("ix_question_version_question_id", table_name="question_version")
    op.drop_index("ix_question_topic_topic_id", table_name="question_topic")
    op.drop_index("ix_question_topic_question_id", table_name="question_topic")
    op.drop_index("ix_question_tag_tag_id", table_name="question_tag")
    op.drop_index("ix_question_tag_question_id", table_name="question_tag")
    op.drop_index("ix_question_report_student_id", table_name="question_report")
    op.drop_index("ix_question_report_question_id", table_name="question_report")
    op.drop_index("ix_activity_student_time", table_name="activity_event")
    op.drop_index("ix_activity_event_student_id", table_name="activity_event")
    op.drop_index("ix_activity_event_session_id", table_name="activity_event")
    op.drop_index("ix_activity_event_occurred_at", table_name="activity_event")
    op.drop_index("ix_activity_event_event_type", table_name="activity_event")
    op.drop_index("ix_activity_event_context_id", table_name="activity_event")
    op.drop_index("ix_activity_event_category", table_name="activity_event")
    op.drop_index("ix_activity_category", table_name="activity_event")
    op.drop_index("ix_vocabulary_translation_entry_id", table_name="vocabulary_translation")
    op.drop_index("ix_vocab_translation_entry_lang", table_name="vocabulary_translation")
    op.drop_index("ix_vocabulary_example_entry_id", table_name="vocabulary_example")
    op.drop_index("ix_reading_question_set_reading_id", table_name="reading_question_set")
    op.drop_index("ix_question_type_status", table_name="question")
    op.drop_index("ix_question_type", table_name="question")
    op.drop_index("ix_question_source_file_id", table_name="question")
    op.drop_index("ix_question_reading_id", table_name="question")
    op.drop_index("ix_question_listening_id", table_name="question")
    op.drop_index("ix_question_level_lang", table_name="question")
    op.drop_index("ix_question_level", table_name="question")
    op.drop_index("ix_question_learning_language", table_name="question")
    op.drop_index("ix_listening_question_set_listening_id", table_name="listening_question_set")
    op.drop_index("ix_import_item_job_id", table_name="import_item")
    op.drop_index("ix_vocabulary_entry_word", table_name="vocabulary_entry")
    op.drop_index("ix_vocabulary_entry_learning_language", table_name="vocabulary_entry")
    op.drop_index("ix_student_session_student_id", table_name="student_session")
    op.drop_index("ix_student_session_session_id", table_name="student_session")
    op.drop_index("ix_student_session_active", table_name="student_session")
    op.drop_index("ix_student_note_student_id", table_name="student_note")
    op.drop_index("uq_student_access_key_active", table_name="student_access_key")
    op.drop_index("ix_student_access_key_student_id", table_name="student_access_key")
    op.drop_index("ix_reading_language", table_name="reading")
    op.drop_index("ix_notification_student_id", table_name="notification")
    op.drop_index("ix_notification_kind", table_name="notification")
    op.drop_index("ix_notif_unread", table_name="notification")
    op.drop_index("ix_listening_language", table_name="listening")
    op.drop_index("ix_import_job_source_file_id", table_name="import_job")
    op.drop_index("ix_group_membership_student_id", table_name="group_membership")
    op.drop_index("ix_group_membership_group_id", table_name="group_membership")
    op.drop_index("ix_favorite_unique", table_name="favorite")
    op.drop_index("ix_favorite_student_id", table_name="favorite")
    op.drop_index("ix_favorite_ref_id", table_name="favorite")
    op.drop_index("ix_exam_section_exam_id", table_name="exam_section")
    op.drop_index("ix_exam_attempt_student_id", table_name="exam_attempt")
    op.drop_index("ix_exam_attempt_session_id", table_name="exam_attempt")
    op.drop_index("ix_exam_attempt_exam_id", table_name="exam_attempt")
    op.drop_index("ix_exam_assignment_student_id", table_name="exam_assignment")
    op.drop_index("ix_exam_assignment_group_id", table_name="exam_assignment")
    op.drop_index("ix_exam_assignment_exam_id", table_name="exam_assignment")
    op.drop_index("ix_assignment_target", table_name="exam_assignment")
    op.drop_index("ix_catalog_item_ref_id", table_name="catalog_item")
    op.drop_index("ix_catalog_item_order", table_name="catalog_item")
    op.drop_index("ix_catalog_item_catalog_id", table_name="catalog_item")
    op.drop_index("ix_admin_recovery_code_admin_id", table_name="admin_recovery_code")
    op.drop_index("ix_topic_parent_name", table_name="topic")
    op.drop_index("ix_topic_parent_id", table_name="topic")
    op.drop_index("ix_tag_name", table_name="tag")
    op.drop_index("ix_system_setting_category", table_name="system_setting")
    op.drop_index("ix_student_username", table_name="student")
    op.drop_index("ix_student_status_deleted", table_name="student")
    op.drop_index("ix_media_asset_checksum", table_name="media_asset")
    op.drop_index("ix_language_code", table_name="language")
    op.drop_index("ix_exam_learning_language", table_name="exam")
    op.drop_index("ix_catalog_parent_id", table_name="catalog")
    op.drop_index("ix_catalog_learning_language", table_name="catalog")
    op.drop_index("ix_audit_log_target_id", table_name="audit_log")
    op.drop_index("ix_audit_log_actor_id", table_name="audit_log")
    op.drop_index("ix_audit_log_action", table_name="audit_log")
    op.drop_index("ix_audit_actor_time", table_name="audit_log")
    op.drop_index("ix_admin_user_username", table_name="admin_user")
    op.drop_table("teacher_feedback")
    op.drop_table("manual_review")
    op.drop_table("attempt_answer")
    op.drop_table("exam_item")
    op.drop_table("question_version")
    op.drop_table("question_topic")
    op.drop_table("question_tag")
    op.drop_table("question_report")
    op.drop_table("activity_event")
    op.drop_table("vocabulary_translation")
    op.drop_table("vocabulary_tag")
    op.drop_table("vocabulary_example")
    op.drop_table("reading_question_set")
    op.drop_table("question")
    op.drop_table("listening_question_set")
    op.drop_table("import_item")
    op.drop_table("vocabulary_entry")
    op.drop_table("student_session")
    op.drop_table("student_note")
    op.drop_table("student_access_key")
    op.drop_table("reading")
    op.drop_table("notification")
    op.drop_table("listening")
    op.drop_table("import_job")
    op.drop_table("group_membership")
    op.drop_table("favorite")
    op.drop_table("export_job")
    op.drop_table("exam_section")
    op.drop_table("exam_attempt")
    op.drop_table("exam_assignment")
    op.drop_table("catalog_item")
    op.drop_table("admin_recovery_code")
    op.drop_table("topic")
    op.drop_table("tag")
    op.drop_table("system_setting")
    op.drop_table("student")
    op.drop_table("source_file")
    op.drop_table("media_asset")
    op.drop_table("language")
    op.drop_table("group")
    op.drop_table("exam")
    op.drop_table("catalog")
    op.drop_table("backup")
    op.drop_table("audit_log")
    op.drop_table("admin_user")
